version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: install ant and maven
          command: |
            sudo apt-get update  
            sudo apt-get install -y ant
            sudo apt-get install-y maven
      - run:
          name: build the project
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package

workflows:
  build-workflow:
    jobs:
      - build